/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src.test.java.Pricewatcher;

import org.junit.Test;

import static org.junit.Assert.*;

public class AppTest {

    String greeting = "hello";

    public String AppTest(){
        return greeting;
    }

    public String getGreeting(){
        return AppTest();
    }


    @Test
    public void testGreeting(){
        AppTest classUnderTest = new AppTest();
        System.out.println("app must have a greeting");
        assertNotNull("app must have a greeting", classUnderTest.getGreeting());
    }
}
